"""Shadow Trading Module.

Runs strategy signals alongside real market data WITHOUT sending real orders.
Generates theoretical orders, tracks theoretical positions/PnL, and produces
comparison reports against backtest results or buy-and-hold benchmarks.
"""
from __future__ import annotations

import logging
import threading
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

import numpy as np
import pandas as pd

from core.strategy.engine import run_signal_fn

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class TheoreticalOrder:
    """A paper order generated by shadow trading — never sent to a broker."""
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    symbol: str = ""
    side: str = "buy"           # "buy" | "sell"
    qty: float = 0.0
    price: float = 0.0
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    signal_reason: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "symbol": self.symbol,
            "side": self.side,
            "qty": self.qty,
            "price": round(self.price, 4),
            "timestamp": self.timestamp.isoformat(),
            "signal_reason": self.signal_reason,
        }


@dataclass
class _ShadowPosition:
    """Internal position tracker for a single symbol."""
    symbol: str
    qty: float = 0.0
    avg_cost: float = 0.0
    current_price: float = 0.0
    realized_pnl: float = 0.0

    @property
    def market_value(self) -> float:
        return self.qty * self.current_price

    @property
    def unrealized_pnl(self) -> float:
        if self.qty <= 0:
            return 0.0
        return (self.current_price - self.avg_cost) * self.qty

    def update_price(self, price: float) -> None:
        self.current_price = price


# ---------------------------------------------------------------------------
# TheoreticalPortfolio
# ---------------------------------------------------------------------------

class TheoreticalPortfolio:
    """Paper portfolio that tracks cash, positions, and PnL without real orders."""

    def __init__(self, init_cash: float = 100_000.0) -> None:
        self._init_cash = init_cash
        self._cash = init_cash
        self._positions: dict[str, _ShadowPosition] = {}
        self._orders: list[TheoreticalOrder] = []

    # -- properties ----------------------------------------------------------

    @property
    def cash(self) -> float:
        return self._cash

    @property
    def invested(self) -> float:
        return sum(p.market_value for p in self._positions.values())

    @property
    def equity(self) -> float:
        return self._cash + self.invested

    @property
    def pnl(self) -> float:
        return self.equity - self._init_cash

    @property
    def positions(self) -> dict[str, _ShadowPosition]:
        return dict(self._positions)

    # -- mutations -----------------------------------------------------------

    def open_position(self, symbol: str, qty: float, price: float, timestamp: datetime | None = None) -> TheoreticalOrder:
        """Buy *qty* shares of *symbol* at *price*."""
        symbol = symbol.upper()
        cost = qty * price
        if cost > self._cash:
            raise ValueError(
                f"Insufficient cash: need {cost:.2f} but have {self._cash:.2f}"
            )
        self._cash -= cost

        pos = self._positions.get(symbol)
        if pos is None:
            pos = _ShadowPosition(symbol=symbol)
            self._positions[symbol] = pos

        total_qty = pos.qty + qty
        if total_qty > 0:
            pos.avg_cost = (pos.avg_cost * pos.qty + price * qty) / total_qty
        pos.qty = total_qty
        pos.update_price(price)

        order = TheoreticalOrder(
            symbol=symbol,
            side="buy",
            qty=qty,
            price=price,
            timestamp=timestamp or datetime.now(timezone.utc),
            signal_reason="open",
        )
        self._orders.append(order)
        return order

    def close_position(self, symbol: str, qty: float, price: float, timestamp: datetime | None = None) -> TheoreticalOrder:
        """Sell *qty* shares of *symbol* at *price*."""
        symbol = symbol.upper()
        pos = self._positions.get(symbol)
        if pos is None or pos.qty < qty:
            have = pos.qty if pos else 0.0
            raise ValueError(f"Insufficient position: {symbol} (have {have}, need {qty})")

        realized = (price - pos.avg_cost) * qty
        pos.realized_pnl += realized
        self._cash += qty * price
        pos.qty -= qty
        if pos.qty <= 0:
            del self._positions[symbol]
        else:
            pos.update_price(price)

        order = TheoreticalOrder(
            symbol=symbol,
            side="sell",
            qty=qty,
            price=price,
            timestamp=timestamp or datetime.now(timezone.utc),
            signal_reason="close",
        )
        self._orders.append(order)
        return order

    def update_prices(self, prices: dict[str, float]) -> None:
        """Mark-to-market all held positions."""
        for symbol, pos in self._positions.items():
            if symbol in prices:
                pos.update_price(prices[symbol])

    def get_theoretical_orders(self) -> list[TheoreticalOrder]:
        """Return all generated orders (read-only copy)."""
        return list(self._orders)


# ---------------------------------------------------------------------------
# ComparisonReport
# ---------------------------------------------------------------------------

@dataclass
class ComparisonReport:
    """Statistical comparison between two return series."""
    shadow_return_pct: float = 0.0
    benchmark_return_pct: float = 0.0
    shadow_sharpe: float = 0.0
    benchmark_sharpe: float = 0.0
    shadow_max_dd: float = 0.0
    benchmark_max_dd: float = 0.0
    correlation: float = 0.0
    tracking_error: float = 0.0
    alpha: float = 0.0
    beta: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "shadow_return_pct": round(self.shadow_return_pct, 4),
            "benchmark_return_pct": round(self.benchmark_return_pct, 4),
            "shadow_sharpe": round(self.shadow_sharpe, 4),
            "benchmark_sharpe": round(self.benchmark_sharpe, 4),
            "shadow_max_dd": round(self.shadow_max_dd, 4),
            "benchmark_max_dd": round(self.benchmark_max_dd, 4),
            "correlation": round(self.correlation, 4),
            "tracking_error": round(self.tracking_error, 4),
            "alpha": round(self.alpha, 6),
            "beta": round(self.beta, 4),
        }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _max_drawdown(equity: pd.Series) -> float:
    """Maximum drawdown as a negative fraction (e.g. -0.15 = -15%)."""
    if equity.empty:
        return 0.0
    cummax = equity.cummax()
    dd = (equity - cummax) / cummax.replace(0, np.nan)
    return float(dd.min()) if not dd.empty else 0.0


def _sharpe(returns: pd.Series, periods_per_year: int = 252) -> float:
    """Annualised Sharpe ratio (risk-free rate assumed 0)."""
    if returns.empty or returns.std() == 0:
        return 0.0
    return float(returns.mean() / returns.std() * np.sqrt(periods_per_year))


def _compute_comparison(
    shadow_equity: pd.Series,
    benchmark_equity: pd.Series,
) -> ComparisonReport:
    """Core statistical comparison between two equity curves."""
    # Align on common index
    combined = pd.DataFrame({
        "shadow": shadow_equity,
        "benchmark": benchmark_equity,
    }).dropna()
    if combined.empty:
        return ComparisonReport()

    shadow_ret = combined["shadow"].pct_change().dropna()
    bench_ret = combined["benchmark"].pct_change().dropna()

    # Align returns
    min_len = min(len(shadow_ret), len(bench_ret))
    shadow_ret = shadow_ret.iloc[:min_len]
    bench_ret = bench_ret.iloc[:min_len]

    report = ComparisonReport()

    # Total return %
    report.shadow_return_pct = (combined["shadow"].iloc[-1] / combined["shadow"].iloc[0] - 1) * 100
    report.benchmark_return_pct = (combined["benchmark"].iloc[-1] / combined["benchmark"].iloc[0] - 1) * 100

    # Sharpe
    report.shadow_sharpe = _sharpe(shadow_ret)
    report.benchmark_sharpe = _sharpe(bench_ret)

    # Max drawdown
    report.shadow_max_dd = _max_drawdown(combined["shadow"]) * 100
    report.benchmark_max_dd = _max_drawdown(combined["benchmark"]) * 100

    # Correlation
    if min_len > 1:
        report.correlation = float(shadow_ret.corr(bench_ret))

        # Tracking error (annualised std of return differences)
        diff = shadow_ret.values - bench_ret.values
        report.tracking_error = float(np.std(diff) * np.sqrt(252)) * 100

        # CAPM alpha & beta
        cov_matrix = np.cov(shadow_ret.values, bench_ret.values)
        bench_var = cov_matrix[1, 1]
        if bench_var > 0:
            report.beta = float(cov_matrix[0, 1] / bench_var)
            report.alpha = (
                float(shadow_ret.mean() - report.beta * bench_ret.mean()) * 252 * 100
            )

    return report


# ---------------------------------------------------------------------------
# ShadowTrader
# ---------------------------------------------------------------------------

class ShadowTrader:
    """Shadow-trading engine: runs strategy signals in real-time without real orders.

    Parameters
    ----------
    strategy_code : str
        Python source code with a ``generate_signals(close, params)`` function.
    params : dict
        Strategy parameters forwarded to the signal function.
    symbols : list[str]
        Tickers to track.
    init_cash : float
        Starting theoretical cash.
    sizing_pct : float
        Fraction of equity to allocate per position (default 10%).
    """

    def __init__(
        self,
        strategy_code: str,
        params: dict[str, Any],
        symbols: list[str],
        init_cash: float = 100_000.0,
        sizing_pct: float = 0.10,
    ) -> None:
        self._strategy_code = strategy_code
        self._params = params or {}
        self._symbols = [s.upper() for s in symbols]
        self._init_cash = init_cash
        self._sizing_pct = sizing_pct

        self._portfolio = TheoreticalPortfolio(init_cash=init_cash)
        self._running = False
        self._lock = threading.RLock()

        # Per-symbol close-price buffers for signal generation
        self._buffers: dict[str, pd.Series] = {
            s: pd.Series(dtype=float) for s in self._symbols
        }

        # Equity curve: list of (timestamp, equity) tuples
        self._equity_curve: list[dict[str, Any]] = []

    # -- lifecycle -----------------------------------------------------------

    def start(self) -> None:
        """Begin accepting bars."""
        with self._lock:
            if self._running:
                return
            # Validate strategy code eagerly
            run_signal_fn(pd.Series(dtype=float), self._strategy_code, self._params)
            self._running = True
            logger.info("ShadowTrader started for %s", self._symbols)

    def stop(self) -> None:
        """Stop accepting bars."""
        with self._lock:
            self._running = False
            logger.info("ShadowTrader stopped")

    @property
    def is_running(self) -> bool:
        return self._running

    # -- bar processing ------------------------------------------------------

    def process_bar(self, bar: dict[str, Any]) -> TheoreticalOrder | None:
        """Process a single OHLCV bar and return a theoretical order if signalled.

        Expected bar keys: ``symbol``, ``close`` (float). Optional: ``timestamp``.
        """
        if not self._running:
            return None

        symbol: str = bar.get("symbol", "").upper()
        close_val: float | None = bar.get("close")
        timestamp = bar.get("timestamp")

        if not symbol or close_val is None:
            raise ValueError("Bar must contain 'symbol' and 'close'")
        if symbol not in self._symbols:
            return None

        with self._lock:
            # Accumulate close prices
            buf = self._buffers[symbol]
            new_point = pd.Series([float(close_val)])
            self._buffers[symbol] = buf = pd.concat([buf, new_point]).tail(500)

            # Need at least a few bars for signals
            if len(buf) < 5:
                self._snapshot_equity(timestamp)
                return None

            # Update portfolio prices
            self._portfolio.update_prices({symbol: float(close_val)})

            # Generate signals
            try:
                entries, exits = run_signal_fn(buf, self._strategy_code, self._params)
            except Exception as exc:
                logger.error("ShadowTrader signal error for %s: %s", symbol, exc)
                self._snapshot_equity(timestamp)
                return None

            has_entry = bool(entries.iloc[-1]) if len(entries) > 0 else False
            has_exit = bool(exits.iloc[-1]) if len(exits) > 0 else False

            ts = timestamp if isinstance(timestamp, datetime) else datetime.now(timezone.utc)
            order: TheoreticalOrder | None = None

            if has_exit and symbol in self._portfolio.positions:
                pos = self._portfolio.positions[symbol]
                order = self._portfolio.close_position(
                    symbol, pos.qty, float(close_val), ts,
                )
                order.signal_reason = "exit_signal"
                logger.info("Shadow EXIT %s qty=%.2f @ %.2f", symbol, pos.qty, close_val)

            elif has_entry and symbol not in self._portfolio.positions:
                equity = self._portfolio.equity
                alloc = equity * self._sizing_pct
                qty = int(alloc / float(close_val))
                if qty > 0:
                    try:
                        order = self._portfolio.open_position(
                            symbol, qty, float(close_val), ts,
                        )
                        order.signal_reason = "entry_signal"
                        logger.info(
                            "Shadow ENTRY %s qty=%d @ %.2f", symbol, qty, close_val,
                        )
                    except ValueError as exc:
                        logger.warning("Shadow open_position skipped: %s", exc)

            self._snapshot_equity(ts)
            return order

    # -- state & analytics ---------------------------------------------------

    def get_shadow_state(self) -> dict[str, Any]:
        """Return full shadow-trading state snapshot."""
        with self._lock:
            return {
                "equity": round(self._portfolio.equity, 2),
                "cash": round(self._portfolio.cash, 2),
                "pnl": round(self._portfolio.pnl, 2),
                "positions": {
                    sym: {
                        "qty": p.qty,
                        "avg_cost": round(p.avg_cost, 4),
                        "current_price": round(p.current_price, 4),
                        "market_value": round(p.market_value, 2),
                        "unrealized_pnl": round(p.unrealized_pnl, 2),
                        "realized_pnl": round(p.realized_pnl, 2),
                    }
                    for sym, p in self._portfolio.positions.items()
                },
                "orders_count": len(self._portfolio.get_theoretical_orders()),
                "running": self._running,
                "symbols": list(self._symbols),
            }

    def get_equity_curve(self) -> list[dict[str, Any]]:
        """Return list of {timestamp, equity} dicts."""
        with self._lock:
            return list(self._equity_curve)

    def get_theoretical_orders(self) -> list[TheoreticalOrder]:
        """Return all generated orders."""
        with self._lock:
            return self._portfolio.get_theoretical_orders()

    # -- comparison ----------------------------------------------------------

    @staticmethod
    def compare_with_backtest(
        shadow_results: dict[str, Any],
        backtest_results: dict[str, Any],
    ) -> ComparisonReport:
        """Compare shadow equity curve with a backtest equity curve.

        Both inputs should contain ``equity_curve`` as a list of dicts with
        ``timestamp`` and ``equity`` keys.
        """
        shadow_eq = _equity_from_results(shadow_results)
        backtest_eq = _equity_from_results(backtest_results)
        return _compute_comparison(shadow_eq, backtest_eq)

    @staticmethod
    def compare_with_buyhold(
        shadow_results: dict[str, Any],
        benchmark_data: pd.Series | dict[str, Any],
    ) -> ComparisonReport:
        """Compare shadow equity curve with a buy-and-hold benchmark.

        ``benchmark_data`` can be a pd.Series of prices or a dict with an
        ``equity_curve`` key.
        """
        shadow_eq = _equity_from_results(shadow_results)
        if isinstance(benchmark_data, pd.Series):
            bench_eq = benchmark_data.sort_index()
        else:
            bench_eq = _equity_from_results(benchmark_data)
        return _compute_comparison(shadow_eq, bench_eq)

    # -- internal helpers ----------------------------------------------------

    def _snapshot_equity(self, timestamp: datetime | None = None) -> None:
        """Append current equity to the curve."""
        self._equity_curve.append({
            "timestamp": (timestamp or datetime.now(timezone.utc)).isoformat()
            if isinstance(timestamp, datetime)
            else str(timestamp),
            "equity": round(self._portfolio.equity, 2),
            "cash": round(self._portfolio.cash, 2),
        })


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _equity_from_results(results: dict[str, Any]) -> pd.Series:
    """Extract a pd.Series equity curve from a results dict."""
    curve = results.get("equity_curve", [])
    if not curve:
        raise ValueError("Results must contain a non-empty 'equity_curve'")

    if isinstance(curve, pd.Series):
        return curve

    equities = [point["equity"] for point in curve]
    timestamps = [point.get("timestamp", i) for i, point in enumerate(curve)]
    return pd.Series(equities, index=timestamps, dtype=float)
